---
- name: Install MariaDB Server
  ansible.builtin.package:
    name: 
      - mariadb-server
      - python3-mysqldb
    state: present
    update_cache: yes

- name: Ensure mariadb service is start
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: yes

- name: Allow external MariaDB connections (1/2)
  ansible.builtin.lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^skip-external-locking'
    line: "# skip-external-locking"
  notify: Restart mysql
  
- name: Allow external MariaDB connections (2/2)
  ansible.builtin.lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^bind-address'
    line: "# bind-address"
  notify: Restart mysql
  
- name: Create MariaDB client config
  ansible.builtin.copy:
    dest: "/root/.my.cnf"
    content: |
      [client]
      user=root
      password={{ root_password }}
    mode: 0400  

- name: Upload MariaDB table config
  ansible.builtin.template:
    src: "table.sql.j2"
    dest: "/tmp/table.sql"

- name: Add MariaDB table to database
  community.mysql.mysql_db:
    name: "{{ mysql_dbname }}"
    state: present
    login_user: root
    login_password: '{{ root_password }}'
    state: import 
    target: /tmp/table.sql

- name: "Create {{ mysql_user }} with all {{ mysql_dbname }} privileges"
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: "{{ mysql_dbname }}.*:ALL"
    host: localhost
    state: present
    login_user: root
    login_password: '{{ root_password }}'
    login_unix_socket: /var/run/mysqld/mysqld.sock
  notify: "Restart MariaBD Serveur"