---
- name: Install Apache and PHP
  ansible.builtin.apt:
    name: ['apache2', 'php', 'php-mysql']
    state: present
    update_cache: yes

- name: Install PHP extra packages
  ansible.builtin.apt:
    name: "{{ php_extra_packages }}"
    state: present

- name: Set up virtualhost
  ansible.builtin.template:
    src: templates/glpi-template.conf
    dest: "/etc/apache2/sites-available/{{ http_conf }}"

# - name: Delete default vhosts in site-enabled
#   ansible.builtin.file:
#     path: "{{ apache_server_conf }}/sites-enabled/{{ item }}"
#     state: absent
#   with_items: "{{ apache_default_vhost_filename }}"
#   notify: Restart apache
#   when: apache_remove_default_vhost
  
# - name: Set up virtualhost
#   ansible.builtin.template:
#     src: templates/glpi-tmp.conf
#     dest: "/etc/apache2/sites-available/glpi.conf"

# - name: Delete default vhosts in site-enabled
#   ansible.builtin.file:
#     path: /etc/apache2/sites-enabled/000-default.conf
#     state: absent

- name: Activate a2enmod rewrite
  ansible.builtin.command: a2enmod rewrite

- name: Enable new site
  #ansible.builtin.command: a2ensite {{  http_conf  }}
  ansible.builtin.command: a2ensite glpi.conf
  notify: "Restart Apache"

- name: Install UFW Firewall
  ansible.builtin.apt:
    name: ufw
    state: present
  notify: "Start UFW"
  
- name: UFW firewall allow HTTP on port {{  http_port  }}
  ufw:
    rule: allow
    port: "{{  http_port  }}"
    proto: tcp
  notify: "Reload UFW"

- name: UFW firewall allow HTTPS on port {{  https_port  }}
  ufw:
    rule: allow
    port: "{{  https_port  }}"
    proto: tcp
  notify: "Reload UFW"
