---
- name: Download and unarchive GLPI archive
  ansible.builtin.unarchive:
    src: https://github.com/glpi-project/glpi/releases/download/10.0.10/glpi-10.0.10.tgz
    dest: /var/www/
    owner: www-data
    group: www-data
    remote_src: yes

- name: GLPI installation
  command: 
    "php bin/console -n db:install -H {{  glpi_db_host  }} -P {{  glpi_db_port  }} -d {{  glpi_db_name  }} -u {{  glpi_db_user  }} -p {{  glpi_db_password  }} --reconfigure --force"
  args:
    chdir: "{{  glpi_install_path  }}"

- name: Clean install.php file
  ansible.builtin.file:
    path: /var/www/glpi/install/install.php
    state: absent
  
