---

apache_service: apache2
apache_daemon: apache2
apache_daemon_path: /usr/sbin/
apache_server_root: /etc/apache2
apache_conf_path: /etc/apache2

# if available, always use the package name with specific
# php version. otherwise the latest available version
# might be installed in conflict with the set {{ php_version }}
__apache_packages:
  - apache2
  - php
  - php-mysql
  - php-curl
  - php-gd
  - php-mbstring

apache_default_vhost_filename: 000-default.conf

apache_ports_configuration_items:
  - regexp: "^Listen "
    line: "Listen {{ apache_listen_port }}"