---
- name: Backup TFTP IOS image
  hosts: ios
  connection: ansible.netcommon.network_cli
  
  vars:
    tftp_ip: 172.16.3.242
  
  tasks:

    - name: Collect gather facts
      cisco.ios.ios_facts:
    
    - name: Config transfert settings
      cisco.ios.ios_config:
        lines:
          - file prompt quiet

    - name: "Use of Ios commands"
      cisco.ios.ios_command:
      #prompt: 'Clear "show interface" counters on this interface \[confirm\]'
        #commands: "copy {{  ansible_net_image  }} tftp://{{  tftp_ip  }}"
        commands: "copy {{  ansible_net_image  }}"
        prompt: 'Address or name of remote host []?'
        answer: "{{  tftp_ip  }}"
        prompt: '[{{  ansible_net_image  }}]?'
        answer: '\r'
    
    # - name: Save IOS image
    #   cisco.ios.ios_command:
    #     commands: "copy {{  ansible_net_image  }} tftp://{{  tftp_ip  }}"
